import sys
import os
import requests
from tqdm import tqdm
import multiprocessing as mlp

# EN_SPKS = [
#     "mars_william",
#     "mars_wendy",
#     "mars_olivia",
#     "mars_luna",
#     "mars_emily",
#     "mars_luca",
#     "mars_harry",
#     "mars_eric",
#     "mars_andy",
#     "mars_abby",
#     "mercury_aria",
#     "mercury_jenny",
#     "mercury_guy",
#     "mercury_aria@narration-professional",
#     "mercury_aria@empathetic",
#     "mercury_aria@cheerful",
#     "mercury_aria@customerservice",
#     "mercury_aria@chat",
#     "mercury_aria@newscast-formal",
#     "mercury_aria@newscast-casual",
#     "mercury_jenny@assistant",
#     "mercury_jenny@chat",
#     "mercury_jenny@customerservice",
#     "mercury_jenny@newscast",
#     "mercury_guy@newscast",
#     "mercury_clara",
#     "mercury_liam",
#     "mercury_libby",
#     "mercury_ryan",
#     "mercury_mia",
#     "mercury_sam",
#     "mercury_yan",
#     "mercury_connor",
#     "mercury_emily",
#     "mercury_neerja",
#     "mercury_prabhat",
#     "mercury_mitchell",
#     "mercury_molly",
#     "mercury_james",
#     "mercury_luna",
#     "mercury_wayne",
#     "mercury_amber",
#     "mercury_ana",
#     "mercury_brandon",
#     "mercury_christopher",
#     "mercury_cora",
#     "mercury_elizabeth",
#     "mercury_eric",
#     "mercury_jacob",
#     "mercury_michelle",
#     "mercury_monica",
#     "mercury_leah",
#     "mercury_ashley",
#     "mercury_sonia",
#     "mercury_asilia",
#     "mercury_chilemba",
#     "mercury_elimu",
#     "mercury_imani",
#     "mercury_abeo",
#     "mercury_ezinne",
#     "mercury_luke",
#     "mercury_jenny@angry",
#     "mercury_jenny@cheerful",
#     "mercury_jenny@sad",
#     "mercury_jenny@excited",
#     "mercury_jenny@friendly",
#     "mercury_jenny@terrified",
#     "mercury_jenny@shouting",
#     "mercury_jenny@unfriendly",
#     "mercury_jenny@whispering",
#     "mercury_jenny@hopeful",
#     "mercury_guy@cheerful",
#     "mercury_guy@angry",
#     "mercury_guy@sad",
#     "mercury_guy@excited",
#     "mercury_guy@friendly",
#     "mercury_guy@terrified",
#     "mercury_guy@shouting",
#     "mercury_guy@unfriendly",
#     "mercury_guy@whispering",
#     "mercury_guy@hopeful",
#     "mercury_aria@excited",
#     "mercury_aria@friendly",
#     "mercury_aria@terrified",
#     "mercury_aria@unfriendly",
#     "mercury_aria@whispering",
#     "mercury_aria@sad",
#     "mercury_aria@angry",
#     "mercury_aria@shouting",
#     "mercury_sara@excited",
#     "mercury_sara@friendly",
#     "mercury_sara@hopeful",
#     "mercury_sara@shouting",
#     "mercury_sara@terrified",
#     "mercury_sara@unfriendly",
#     "mercury_sara@whispering",
#     "mercury_aria@hopeful"
# ]

EN_SPKS = [
    "mars_william",
    "mars_wendy",
    "mars_olivia",
    "mars_luna",
    "mars_emily",
    "mars_luca",
    "mars_harry",
    "mars_eric",
    "mars_andy",
    "mars_abby",
    "mercury_aria",
    "mercury_jenny",
    "mercury_guy",
    "mercury_aria@narration-professional",
    "mercury_aria@empathetic",
    "mercury_aria@cheerful",
    "mercury_aria@customerservice",
    "mercury_aria@chat",
    "mercury_aria@newscast-formal",
    "mercury_aria@newscast-casual",
    "mercury_jenny@assistant",
    "mercury_jenny@chat",
    "mercury_jenny@customerservice",
    "mercury_jenny@newscast"
]
# EN_TEXTS = [
#     "mark that", "mark", "that", 
#     "shut down camera", "shut down", "shut", "down camera", "camera",
#     "start recording", "start", "recording",
#     "stop recording", "stop",
#     "take a photo", "take a", "take", "a photo", "photo"
# ]

EN_TEXTS = [
    "open the door", "close the door"
]

YUE_SPKS = [
    "dora_lpcnet_24k",
    "mercury_hiugaai",
    "mars_shanshan",
    "mercury_hiumaan",
    "mercury_wanlung",
    "mars_jiajia",
]

YUE_TEXTS = [
    "粤语测试",
    "机器越来越小、便携、移动，人机交互方式必然会更智能、更高效",
    "定义下一代人机交互，让人和机器的交互更高效智能",
    "科技使人自由和社会进步",
    "我们要成为强执行力的创新型科技组织"
]

CHUAN_SPKS =[
    "baoer_lpcnet_24k",
    "mars_chuangirl",
    "moxiaoxi_lpcnet_24k",
    "mercury_sc-yunxi",
]

CHUAN_TEXTS = [
    "四川话测试",
    "机器越来越小、便携、移动，人机交互方式必然会更智能、更高效",
    "定义下一代人机交互，让人和机器的交互更高效智能",
    "科技使人自由和社会进步",
    "我们要成为强执行力的创新型科技组织"
]

ZHONG_SPKS = [
    "lucy_lpcnet_24k",
    "cissy_lpcnet_24k",
    "yingqiong_lpcnet_24k",
    "ajiao_lpcnet_24k",
    "weiwei_lpcnet_24k",
    "arou_lpcnet_24k",
    "alan_lpcnet_24k",
    "chunchun_lpcnet_24k",
    "huier_lpcnet_24k",
    "linger_lpcnet_24k",
    "shujun_lpcnet_24k",
    "lili_lpcnet_24k",
    "wenwen_lpcnet_24k",
    "xiaoqing_lpcnet_24k",
    "miaomiao_lpcnet_24k",
    "aya_lpcnet_24k",
    "xiaoyan_lpcnet_24k",
    "yuer_lpcnet_24k",
    "lanxin_lpcnet_24k",
    "qiqi_lpcnet_24k",
    "lingling_lpcnet_24k",
    "zhuanger_lpcnet_24k",
    "xiaohu_lpcnet_24k",
    "boguang_lpcnet_24k",
    "murong_lpcnet_24k",
    "yuge_lpcnet_24k",
    "emily_lpcnet_24k",
    "king_lpcnet",
    "danqing_lpcnet_24k",
    "billy_lpcnet_24k",
    "guangmingfemale_lpcnet_24k",
    "guangmingmale_lpcnet_24k",
    "F110_lpcnet_24k",
    "amo_lpcnet_24k",
    "xiaoshuang_lpcnet_24k",
    "bingbing_lpcnet_24k",
    "mercury_xiaoxiao",
    "mercury_xiaoyou",
    "mercury_yunyang",
    "mercury_yunye",
    "mercury_xiaoxiao@newscast",
    "mercury_xiaoxiao@customerservice",
    "mercury_xiaoxiao@assistant",
    "mercury_xiaoxiao@chat",
    "mercury_xiaoxiao@calm",
    "mercury_xiaoxiao@cheerful",
    "mercury_xiaoxiao@sad",
    "mercury_xiaoxiao@angry",
    "mercury_xiaoxiao@fearful",
    "mercury_xiaoxiao@disgruntled",
    "mercury_xiaoxiao@serious",
    "mercury_xiaoxiao@affectionate",
    "mercury_xiaoxiao@gentle",
    "mercury_xiaoxiao@lyrical",
    "mars_aida",
    "mars_aicheng",
    "mars_aishuo",
    "mars_sicheng",
    "mars_xiaogang",
    "mars_aichu",
    "mars_aimo",
    "mars_aide",
    "mars_aiye",
    "mars_aihao",
    "mars_ainan",
    "mars_aixiang",
    "mars_aiming",
    "mars_xiaoze",
    "mars_cuijie",
    "huangrenhong_lpcnet_24k",
    "venus_zhixia_super",
    "venus_zhiyu_super",
    "shaoniandedao_lpcnet_24k",
    "M109_lpcnet_24k",
    "mercury_yunxi",
    "mercury_yunxi@cheerful",
    "mercury_yunxi@calm",
    "mercury_yunxi@sad",
    "mercury_yunxi@angry",
    "mercury_yunxi@fearful",
    "mercury_yunxi@disgruntled",
    "mercury_yunxi@serious",
    "mercury_yunxi@depressed",
    "mercury_yunxi@embarrassed",
    "mercury_xiaohan",
    "mercury_xiaohan@cheerful",
    "mercury_xiaohan@sad",
    "mercury_xiaohan@calm",
    "mercury_xiaohan@angry",
    "mercury_xiaohan@fearful",
    "mercury_xiaohan@disgruntled",
    "mercury_xiaohan@serious",
    "mercury_xiaohan@embarrassed",
    "mercury_xiaohan@affectionate",
    "mercury_xiaohan@gentle",
    "mercury_xiaomo",
    "mercury_xiaomo@cheerful",
    "mercury_xiaomo@angry",
    "mercury_xiaomo@calm",
    "mercury_xiaomo@fearful",
    "mercury_xiaomo@disgruntled",
    "mercury_xiaomo@serious",
    "mercury_xiaomo@depressed",
    "mercury_xiaomo@gentle",
    "mercury_xiaoxuan",
    "mercury_xiaoxuan@cheerful",
    "mercury_xiaoxuan@angry",
    "mercury_xiaoxuan@calm",
    "mercury_xiaoxuan@fearful",
    "mercury_xiaoxuan@disgruntled",
    "mercury_xiaoxuan@serious",
    "mercury_xiaoxuan@depressed",
    "mercury_xiaoxuan@gentle",
    "mercury_xiaorui",
    "mercury_xiaorui@sad",
    "mercury_xiaorui@calm",
    "mercury_xiaorui@angry",
    "mercury_xiaorui@fearful",
    "mercury_xiaoyou@chat",
    "mercury_yunye@calm",
    "mercury_yunye@serious",
    "mercury_yunye@sad",
    "yangchongsheng_lpcnet_24k",
    "m026_lpcnet_24k",
    "venus_zhixia",
    "fengxiaoying_lpcnet_24k",
    "xiaoqun_lpcnet_24k",
    "wangduo_lpcnet_24k",
    "moxiaofeng_lpcnet_24k",
    "wuhan037_lpcnet_24k",
    "jikexiaoxing_lpcnet_24k",
    "m091_lpcnet_24k",
    "bingbing_lpcnet_24k@cheerful",
    "bingbing_lpcnet_24k@sad",
    "zhongxinxiaoke_lpcnet_24k",
    "weini_lpcnet_24k",
    "labixiaoxin_lpcnet_24k",
    "libai_lpcnet_24k",
    "yujie_lpcnet_24k",
    "yangguang_lpcnet_24k",
    "yangjingv_lpcnet_24k@xuanyi",
    "lin_lpcnet_24k",
    "m026_lpcnet_24k@cheerful",
    "m026_lpcnet_24k@sad",
    "m026_lpcnet_24k@angry",
    "m026_lpcnet_24k@fearful",
    "m026_lpcnet_24k@lyrical",
    "m026_lpcnet_24k@surprise",
    "moyuxia_lpcnet_24k",
    "molingluo_lpcnet_24k",
    "venus_zhimeng",
    "venus_zhitian",
    "venus_zhihui",
    "venus_zhijing_super",
    "motianqi_lpcnet_24k",
    "mobeixuan_lpcnet_24k",
    "molingyun_lpcnet_24k",
    "shizhongxian_lpcnet_24k",
    "liuneng_lpcnet_24k",
    "ligev5_lpcnet_24k",
    "mercury_yunyang@narration",
    "mercury_yunyang@customerservice",
    "mojie_lpcnet_24k",
    "moyi_lpcnet_24k",
    "billy_lpcnet_24k@warm",
    "bingbing_lpcnet_24k@warm",
    "bingbing_lpcnet_24k@original",
    "bingbing_lpcnet_24k@noble",
    "huazai_lpcnet_24k@shengdong",
    "murong_lpcnet_24k@warm",
    "murong_lpcnet_24k@original",
    "moyi_lpcnet_24k@conversation",
    "mokasha_lpcnet_24k",
    "moyili_lpcnet_24k",
    "baibianjianzhang_lpcnet_24k@fuhei",
    "baibianjianzhang_lpcnet_24k@chenwen",
    "baibianjianzhang_lpcnet_24k@boxue",
    "baibianjianzhang_lpcnet_24k@hualao",
    "m026_lpcnet_24k@warm",
    "m091_lpcnet_24k@vivid",
    "m091_lpcnet_24k@old",
    "xiaoshuang_lpcnet_24k@old",
    "m026_lpcnet_24k@sweet",
    "m091_lpcnet_24k@sweet",
    "moyili_lpcnet_24k@warm",
    "jinshilaoshi_lpcnet_24k",
    "moxiaoqi_lpcnet_24k@classic",
    "murong_lpcnet_24k@old",
    "m026_lpcnet_24k@old",
    "moxidu_lpcnet_24k",
    "motianqi_lpcnet_24k@original",
    "motianqi_lpcnet_24k@warm",
    "moyili_lpcnet_24k@lovely",
    "moyili_lpcnet_24k@vivid",
    "moxidu_lpcnet_24k@old",
    "moxidu_lpcnet_24k@vivid",
    "moxidu_lpcnet_24k@original",
    "moxidu_lpcnet_24k@warm",
    "baibianjianzhang_lpcnet_24k@villain",
    "baibianjianzhang_lpcnet_24k@warm",
    "baibianjianzhang_lpcnet_24k@cheerful",
    "baibianjianzhang_lpcnet_24k@sad",
    "emily_lpcnet_24k@noble",
    "F110_lpcnet_24k@noble",
    "jinshilaoshi_lpcnet_24k@old",
    "moqianxue_lpcnet_24k",
    "moqianxue_lpcnet_24k@warm",
    "mercury_yunxi@assistant",
    "mercury_yunye@angry",
    "mercury_yunye@disgruntled",
    "mercury_yunye@fearful",
    "moxidu_lpcnet_24k@classic",
    "caicai_lpcnet_24k",
    "xiaoman_lpcnet_24k",
    "baibianjianzhang_lpcnet_24k@jingqiang",
    "moqianxue_lpcnet_24k@classic",
    "m091_lpcnet_24k@daxia",
    "modongxie_lpcnet_24k",
    "moxidu_lpcnet_24k@lyrical",
    "moxidu_lpcnet_24k@sad",
    "mobeigai_lpcnet_24k",
    "mochuideng_lpcnet_24k",
    "m091_lpcnet_24k@sports",
    "mowenya_lpcnet_24k",
    "moxinyi_lpcnet_24k",
    "moyingying_lpcnet_24k",
    "monihong_lpcnet_24k",
    "caicai_lpcnet_24k@qinghua",
    "monihong_lpcnet_24k@newscast",
    "mowenya_lpcnet_24k@shenchen",
    "moxidu_lpcnet_24k@honest",
    "moxidu_lpcnet_24k@chic",
    "wuhan037_lpcnet_24k@vivid",
    "wuhan037_lpcnet_24k@warm",
    "mokasha_lpcnet_24k@noble",
    "moyili_lpcnet_24k@noble",
    "monihong_lpcnet_24k@sad",
    "cuteelve_lpcnet_24k",
    "motailong_lpcnet_24k",
    "mobotong_lpcnet_24k",
    "moqingzhao_lpcnet_24k",
    "modongpo_lpcnet_24k",
    "mowangshu_lpcnet_24k",
    "mobeigai_lpcnet_24k@warm",
    "moyuji_lpcnet_24k@classic",
    "mojiaxuan_lpcnet_24k",
    "moshaolong_lpcnet_24k",
    "moshuxin_lpcnet_24k",
    "caicai_lpcnet_24k@sad",
    "moxinyi_lpcnet_24k@angry",
    "mobeigai_lpcnet_24k@sports",
    "mowaner_lpcnet_24k",
    "moxinyi_lpcnet_24k@fearful",
    "moxinyi_lpcnet_24k@cheerful",
    "mobeigai_lpcnet_24k@game",
    "minicai_lpcnet_24k",
    "moduidui_lpcnet_24k",
    "moxinyi_lpcnet_24k@sad",
    "modongxie_lpcnet_24k@classic",
    "caicai_lpcnet_24k@food",
    "mohongsheng_lpcnet_24k",
    "molinglong_lpcnet_24k@amusement",
    "molinglong_lpcnet_24k@sentimental",
    "molinglong_lpcnet_24k@kongbu",
    "molinglong_lpcnet_24k@shudan",
    "molinglong_lpcnet_24k",
    "moxinyi_lpcnet_24k@surprise",
    "moxinyi_lpcnet_24k@lyrical",
    "moxinyi_lpcnet_24k@disgruntled",
    "moxiaowan_lpcnet_24k",
    "mohongsheng_lpcnet_24k@shudan",
    "manchaozn_lpcnet_24k",
    "manchaozn_lpcnet_24k@wenqing",
    "manchaozn_lpcnet_24k@passion",
    "manchaozn_lpcnet_24k@daoyou",
    "mowanqing_lpcnet_24k",
    "xiaoman_lpcnet_24k@sad",
    "mowanqing_lpcnet_24k@shudan",
    "molinglong_lpcnet_24k@cheerful",
    "molinglong_lpcnet_24k@wenqing",
    "molinglong_lpcnet_24k@qinggan",
    "mowanqing_lpcnet_24k@novel",
    "molinglong_lpcnet_24k@novel",
    "mohongsheng_lpcnet_24k@ruya",
    "moxiaowannv_lpcnet_24k",
    "mozhongling_lpcnet_24k",
    "modisheng_lpcnet_24k",
    "manchaozn_lpcnet_24k@classic",
    "mowanqing_lpcnet_24k@wenqing",
    "mohongyi_lpcnet_24k",
    "mocuishan_lpcnet_24k",
    "moshutong_lpcnet_24k",
    "moqingshu_lpcnet_24k",
    "molingsha_lpcnet_24k",
    "manchaozn_lpcnet_24k@shudan",
    "mars_laomei",
    "molaotie_lpcnet_24k@classic",
    "mars_xiaoxian",
    "mars_aixia",
    "mars_kenny",
    "mars_lydia",
    "mars_stanley",
    "mars_stella",
    "mars_aibao",
    "moaifei_lpcnet_24k",
    "mars_aijia",
    "mars_aijing",
    "mars_ailun",
    "mars_aimei",
    "mars_aiqi",
    "mars_aitong",
    "mars_aiwei",
    "mars_aiya",
    "mars_aiyue",
    "mars_dahu",
    "mars_guijie",
    "moxidu_lpcnet_24k@default2",
    "molinglong_lpcnet_24k@sad",
    "mars_jielidou",
    "mars_maoxiaomei",
    "mars_mashu",
    "mars_qiaowei",
    "mars_yaqun",
    "manchaozn_lpcnet_24k@jilupian",
    "manchaozn_lpcnet_24k@boya",
    "molingsha_lpcnet_24k@cheerful",
    "caicai_lpcnet_24k@yingshi",
    "molinglong_lpcnet_24k@jilupian",
    "manchaozn_lpcnet_24k@kongbu",
    "manchaozn_lpcnet_24k@guimi",
    "moshuxin_lpcnet_24k@novel",
    "mowanqing_lpcnet_24k@lyrical",
    "mochuideng_lpcnet_24k@novel",
    "mochuideng_lpcnet_24k@sentimental",
    "moshuxin_lpcnet_24k@kehuan",
    "molingsha_lpcnet_24k@lovely",
    "molingsha_lpcnet_24k@kepu",
    "molingsha_lpcnet_24k@shudan",
    "molingsha_lpcnet_24k@jilupian",
    "molinglong_lpcnet_24k@lyrical",
    "molinglong_lpcnet_24k@kehuan",
    "molingji_lpcnet_24k",
    "molingji_lpcnet_24k@wenqing",
    "mosumei_lpcnet_24k",
    "mowanzhu_lpcnet_24k",
    "moxiaowannv_lpcnet_24k@game",
    "manchaozn_lpcnet_24k@chenwen",
    "manchaozn_lpcnet_24k@xili",
    "moshuxin_lpcnet_24k@xuanyi",
    "moshaolong_lpcnet_24k@sumu",
    "caicai_lpcnet_24k@cheerful",
    "mojingtang_lpcnet_24k",
    "mojingtang_lpcnet_24k@dalao",
    "mohexian_lpcnet_24k",
    "moguishu_lpcnet_24k",
    "moxiaofan_lpcnet_24k",
    "mojunyi_lpcnet_24k@qinggan",
    "mojunyi_lpcnet_24k",
    "moyangang_lpcnet_24k",
    "xiaoqing_lpcnet_24k@kongbu",
    "xiaoqing_lpcnet_24k@dongzuo",
    "xiaoqing_lpcnet_24k@xiequ",
    "xiaoqing_lpcnet_24k@vivid",
    "mochuideng_lpcnet_24k@amusement",
    "mozuoyi_lpcnet_24k@cute",
    "mozuoyi_lpcnet_24k@cheerful_v2",
    "moyuji_lpcnet_24k@pingshu",
    "moyingtao_lpcnet_24k",
    "moxiaoqi_lpcnet_24k",
    "mochuideng_lpcnet_24k@jilupian",
    "gjyg_lpcnet_24k",
    "gjyg_lpcnet_24k@guimi",
    "gjyg_lpcnet_24k@kongbu",
    "gjyg_lpcnet_24k@gaoxiao",
    "gjyg_lpcnet_24k@shenmi",
    "gjyg_lpcnet_24k@tale",
    "manchaozn_lpcnet_24k@wuxia",
    "manchaozn_lpcnet_24k@qingliang",
    "gjyg_lpcnet_24k@novel",
    "molingsha_lpcnet_24k@daqi",
    "xiaoqing_lpcnet_24k@warm",
    "moyuji_lpcnet_24k@xuanyi",
    "gjyg_lpcnet_24k@xuanhuan",
    "moxiaose_lpcnet_24k@jilupian",
    "moxiaose_lpcnet_24k",
    "moxiaoqi_lpcnet_24k@zixun",
    "huazai_lpcnet_24k@kongbu",
    "huazai_lpcnet_24k",
    "beier_lpcnet_24k",
    "mozhengchun_lpcnet_24k@sumu",
    "mozhengchun_lpcnet_24k",
    "moxiaoman_lpcnet_24k",
    "modaji_lpcnet_24k",
    "gjyg_lpcnet_24k@gangjing",
    "moshuxin_lpcnet_24k@amusement",
    "moshuxin_lpcnet_24k@food",
    "moxidu_lpcnet_24k@kehuan",
    "moxiaoqi_lpcnet_24k@shadiao",
    "fantian_lpcnet_24k",
    "mars_xiaoyun",
    "molingsha_lpcnet_24k@lyrical",
    "mars_aiyuan",
    "moxiaoqi_lpcnet_24k@food",
    "moxiaoqi_lpcnet_24k@xuanyi",
    "beier_lpcnet_24k@hanju",
    "beier_lpcnet_24k@xuanyi",
    "mars_aiying",
    "huazai_lpcnet_24k@dongbei",
    "venus_zhiyan",
    "venus_zhili_super",
    "venus_zhiyun_sec_super",
    "venus_zhimei_super",
    "venus_zhiling_super",
    "venus_zhixiaoyao_super",
    "mercury_yunye@embarrassed",
    "mars_rosa",
    "mars_taozi",
    "mars_aishu",
    "venus_zhina_super",
    "venus_zhiqi_super",
    "venus_zhiyun_super",
    "venus_zhihua_super",
    "venus_zhiyan_sec",
    "venus_zhidan",
    "venus_zhining",
    "venus_zhirong_super",
    "venus_zhitong",
    "venus_zhigang",
    "venus_zhirui",
    "venus_zhihong",
    "venus_zhixuan",
    "venus_zhihao",
    "venus_zhiwei",
    "venus_zhixi",
    "venus_zhimei_second",
    "venus_zhijie",
    "venus_zhikai",
    "venus_zhike",
    "venus_zhikui",
    "venus_zhifang",
    "venus_zhibei",
    "venus_zhilian",
    "venus_zhiyi",
    "venus_zhichuan",
    "venus_wejack_super",
    "venus_werose_super",
    "molingsha_lpcnet_24k@surprise",
    "moshuxin_lpcnet_24k@sad",
    "moshuxin_lpcnet_24k@lyrical",
    "moshuxin_lpcnet_24k@cheerful",
    "moshuxin_lpcnet_24k@angry",
    "moshuxin_lpcnet_24k@surprise",
    "moshuxin_lpcnet_24k@disgruntled",
    "moxiaofan_lpcnet_24k@dongzuo",
    "moxiaowannv_lpcnet_24k@jiling",
    "moshuxin_lpcnet_24k@fearful",
    "moxiaoman_lpcnet_24k@hanju",
    "huazai_lpcnet_24k@chic",
    "molaofeng_lpcnet_24k",
    "molaofeng_lpcnet_24k@kongbu",
    "xiaoruichen_lpcnet_24k",
    "moxiaosheng_lpcnet_24k",
    "moxiaoman_lpcnet_24k@food",
    "moxie_lpcnet_24k",
    "molingsha_lpcnet_24k@angry",
    "molingsha_lpcnet_24k@sad",
    "kuankuan_lpcnet_24k",
    "moqianchuan_lpcnet_24k",
    "molinglong_lpcnet_24k@fearful",
    "moxiaofan_lpcnet_24k@knowledge",
    "moshuihan_lpcnet_24k",
    "mofangguan_lpcnet_24k",
    "mosiqi_lpcnet_24k",
    "mowuji_lpcnet_24k",
    "molinglong_lpcnet_24k@angry",
    "molinglong_lpcnet_24k@disgruntled",
    "molinglong_lpcnet_24k@surprise",
    "kuankuan_lpcnet_24k@tale",
    "moshuxin_lpcnet_24k@passion",
    "moshuxin_lpcnet_24k@xuanchuan",
    "mowenshu_lpcnet_24k",
    "molingsha_lpcnet_24k@knowledge",
    "mofangguan_lpcnet_24k@cute",
    "mosumei_lpcnet_24k@hanju",
    "caicai_lpcnet_24k@knowledge",
    "caicai_lpcnet_24k@shudan",
    "moshuxin_lpcnet_24k@knowledge",
    "wasi_lpcnet_24k",
    "moxuemei_lpcnet_24k",
    "mercury_xiaochen",
    "fantian_lpcnet_24k@kongbu",
    "wasi_lpcnet_24k@chenwen",
    "mercury_sara@angry",
    "mercury_sara@cheerful",
    "mercury_sara@sad",
    "mercury_sara",
    "mercury_xiaoqiu",
    "mercury_xiaoyan",
    "mercury_xiaoshuang",
    "mercury_xiaoshuang@chat",
]

ZHONG_TEXTS = [
    "小邦小邦",
]
# text_list = ["做个标记", "关闭相机", "开始录像", "停止录像", "拍张照片"]
# text_list = ["做个标记", "做个", "做个标", "关闭相机", "关闭", "关闭相", 
#              "开始录像", "开始", "开始录", "停止录像", "停止", "停止录",
#              "拍张照片", "拍张", "拍张照"]

#简化后的代码：
def get_wav(args):
    url, wav_path, text = args
    response = requests.get(url)
    with open(wav_path, 'wb') as fout:
        fout.write(response.content)
    return (wav_path, text)

def main():
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)

    trans = open(os.path.join(out_dir, "trans"), 'w', encoding='utf-8')

    print("preparing tasks ......")
    pool = mlp.Pool(12)
    base_url = "http://platform-tts-test.mobvoi.com/api/synthesis?audio_type=wav"
    tasks = [(base_url + "&speaker={}&text={}&pitch={}&speed={}&volume={}".format(spr, text, pitch, speed, volume),
              os.path.join(out_dir, spr.replace("@", "_") + '_' + str(i+1) + '_' + str(pitch) + '_' + str(speed) + '_' + str(volume) +".wav"),
              text) 
             for spr in EN_SPKS
             for i, text in enumerate(EN_TEXTS)
             for pitch in [1]
             for speed in [1]
             for volume in [1]
             if not os.path.exists(os.path.join(out_dir, spr.replace("@", "_") + '_' + str(i+1) + '_' + str(pitch) + '_' + str(speed) + '_' + str(volume) +".wav"))]
    
    print("doing tasks ......")
    results = list(tqdm(pool.imap_unordered(get_wav, tasks), total=len(tasks)))
    for result in results:
        trans.write(result[0] + '\t' + result[1] + '\n')

    trans.close()
    print("done")

if __name__ == "__main__":
    main()
            #   for pitch in [-1, 0, 1]
            #  for speed in [0.9, 1, 1.1]
            #  for volume in [-1, -2, 1]   
#原始代码
# def get_wav(url, wav_path):
#     response = requests.get(url)
#     with open(wav_path, 'wb') as fout:
#         fout.write(response.content)


# def main():
#     out_dir = sys.argv[1]
#     if not os.path.exists(out_dir):
#         os.makedirs(out_dir)

#     trans = open(os.path.join(out_dir, "trans"), 'w', encoding='utf-8')

#     print("preparing tasks ......")
#     tasks = []
#     pool = mlp.Pool(12)
#     base_url = "http://platform-tts-test.mobvoi.com/api/synthesis?audio_type=wav"
#     for spr in ZHONG_SPKS:
#         for i, text in enumerate(ZHONG_TEXTS):
#             for pitch in -1,0,1:
#                 for speed in 0.9,1,1.1:
#                     for volume in -1,-2,1:
#                     #print(type(pitch),pitch)
#                         url = base_url + "&speaker={}&text={}&pitch={}&speed={}&volume={}".format(spr, text, pitch, speed, volume)
#                         wav_name = spr.replace("@", "_") + '_' + str(i+1) + '_' + str(pitch) + '_' + str(speed) + '_' + str(volume) +".wav"
#                         wav_path = os.path.join(out_dir, wav_name)
#                         if not os.path.exists(wav_path):
#                             tasks.append(pool.apply_async(get_wav, (url, wav_path)))
#                             trans.write(wav_path + '\t' + text + '\n')
#     trans.close()
#     print("doing tasks ......")
#     for i in tqdm(range(len(tasks))):
#         tasks[i].get()
#     print("done")

# if __name__ == "__main__":
#     main()