# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_filterbank_wrapper', [dirname(__file__)])
        except ImportError:
            import _filterbank_wrapper
            return _filterbank_wrapper
        if fp is not None:
            try:
                _mod = imp.load_module('_filterbank_wrapper', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _filterbank_wrapper = swig_import_helper()
    del swig_import_helper
else:
    import _filterbank_wrapper
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _filterbank_wrapper.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _filterbank_wrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _filterbank_wrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _filterbank_wrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _filterbank_wrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _filterbank_wrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _filterbank_wrapper.SwigPyIterator_copy(self)

    def next(self):
        return _filterbank_wrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _filterbank_wrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _filterbank_wrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _filterbank_wrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _filterbank_wrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _filterbank_wrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _filterbank_wrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _filterbank_wrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _filterbank_wrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _filterbank_wrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _filterbank_wrapper.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VectorFloat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorFloat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _filterbank_wrapper.VectorFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _filterbank_wrapper.VectorFloat___nonzero__(self)

    def __bool__(self):
        return _filterbank_wrapper.VectorFloat___bool__(self)

    def __len__(self):
        return _filterbank_wrapper.VectorFloat___len__(self)

    def __getslice__(self, i, j):
        return _filterbank_wrapper.VectorFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _filterbank_wrapper.VectorFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _filterbank_wrapper.VectorFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _filterbank_wrapper.VectorFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _filterbank_wrapper.VectorFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _filterbank_wrapper.VectorFloat___setitem__(self, *args)

    def pop(self):
        return _filterbank_wrapper.VectorFloat_pop(self)

    def append(self, x):
        return _filterbank_wrapper.VectorFloat_append(self, x)

    def empty(self):
        return _filterbank_wrapper.VectorFloat_empty(self)

    def size(self):
        return _filterbank_wrapper.VectorFloat_size(self)

    def swap(self, v):
        return _filterbank_wrapper.VectorFloat_swap(self, v)

    def begin(self):
        return _filterbank_wrapper.VectorFloat_begin(self)

    def end(self):
        return _filterbank_wrapper.VectorFloat_end(self)

    def rbegin(self):
        return _filterbank_wrapper.VectorFloat_rbegin(self)

    def rend(self):
        return _filterbank_wrapper.VectorFloat_rend(self)

    def clear(self):
        return _filterbank_wrapper.VectorFloat_clear(self)

    def get_allocator(self):
        return _filterbank_wrapper.VectorFloat_get_allocator(self)

    def pop_back(self):
        return _filterbank_wrapper.VectorFloat_pop_back(self)

    def erase(self, *args):
        return _filterbank_wrapper.VectorFloat_erase(self, *args)

    def __init__(self, *args):
        this = _filterbank_wrapper.new_VectorFloat(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _filterbank_wrapper.VectorFloat_push_back(self, x)

    def front(self):
        return _filterbank_wrapper.VectorFloat_front(self)

    def back(self):
        return _filterbank_wrapper.VectorFloat_back(self)

    def assign(self, n, x):
        return _filterbank_wrapper.VectorFloat_assign(self, n, x)

    def resize(self, *args):
        return _filterbank_wrapper.VectorFloat_resize(self, *args)

    def insert(self, *args):
        return _filterbank_wrapper.VectorFloat_insert(self, *args)

    def reserve(self, n):
        return _filterbank_wrapper.VectorFloat_reserve(self, n)

    def capacity(self):
        return _filterbank_wrapper.VectorFloat_capacity(self)
    __swig_destroy__ = _filterbank_wrapper.delete_VectorFloat
    __del__ = lambda self: None
VectorFloat_swigregister = _filterbank_wrapper.VectorFloat_swigregister
VectorFloat_swigregister(VectorFloat)

class VectorVectorFloat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorVectorFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorVectorFloat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _filterbank_wrapper.VectorVectorFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _filterbank_wrapper.VectorVectorFloat___nonzero__(self)

    def __bool__(self):
        return _filterbank_wrapper.VectorVectorFloat___bool__(self)

    def __len__(self):
        return _filterbank_wrapper.VectorVectorFloat___len__(self)

    def __getslice__(self, i, j):
        return _filterbank_wrapper.VectorVectorFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _filterbank_wrapper.VectorVectorFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _filterbank_wrapper.VectorVectorFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _filterbank_wrapper.VectorVectorFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _filterbank_wrapper.VectorVectorFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _filterbank_wrapper.VectorVectorFloat___setitem__(self, *args)

    def pop(self):
        return _filterbank_wrapper.VectorVectorFloat_pop(self)

    def append(self, x):
        return _filterbank_wrapper.VectorVectorFloat_append(self, x)

    def empty(self):
        return _filterbank_wrapper.VectorVectorFloat_empty(self)

    def size(self):
        return _filterbank_wrapper.VectorVectorFloat_size(self)

    def swap(self, v):
        return _filterbank_wrapper.VectorVectorFloat_swap(self, v)

    def begin(self):
        return _filterbank_wrapper.VectorVectorFloat_begin(self)

    def end(self):
        return _filterbank_wrapper.VectorVectorFloat_end(self)

    def rbegin(self):
        return _filterbank_wrapper.VectorVectorFloat_rbegin(self)

    def rend(self):
        return _filterbank_wrapper.VectorVectorFloat_rend(self)

    def clear(self):
        return _filterbank_wrapper.VectorVectorFloat_clear(self)

    def get_allocator(self):
        return _filterbank_wrapper.VectorVectorFloat_get_allocator(self)

    def pop_back(self):
        return _filterbank_wrapper.VectorVectorFloat_pop_back(self)

    def erase(self, *args):
        return _filterbank_wrapper.VectorVectorFloat_erase(self, *args)

    def __init__(self, *args):
        this = _filterbank_wrapper.new_VectorVectorFloat(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _filterbank_wrapper.VectorVectorFloat_push_back(self, x)

    def front(self):
        return _filterbank_wrapper.VectorVectorFloat_front(self)

    def back(self):
        return _filterbank_wrapper.VectorVectorFloat_back(self)

    def assign(self, n, x):
        return _filterbank_wrapper.VectorVectorFloat_assign(self, n, x)

    def resize(self, *args):
        return _filterbank_wrapper.VectorVectorFloat_resize(self, *args)

    def insert(self, *args):
        return _filterbank_wrapper.VectorVectorFloat_insert(self, *args)

    def reserve(self, n):
        return _filterbank_wrapper.VectorVectorFloat_reserve(self, n)

    def capacity(self):
        return _filterbank_wrapper.VectorVectorFloat_capacity(self)
    __swig_destroy__ = _filterbank_wrapper.delete_VectorVectorFloat
    __del__ = lambda self: None
VectorVectorFloat_swigregister = _filterbank_wrapper.VectorVectorFloat_swigregister
VectorVectorFloat_swigregister(VectorVectorFloat)

class FilterbankOptions(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FilterbankOptions, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FilterbankOptions, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _filterbank_wrapper.new_FilterbankOptions()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["feature_channels"] = _filterbank_wrapper.FilterbankOptions_feature_channels_set
    __swig_getmethods__["feature_channels"] = _filterbank_wrapper.FilterbankOptions_feature_channels_get
    if _newclass:
        feature_channels = _swig_property(_filterbank_wrapper.FilterbankOptions_feature_channels_get, _filterbank_wrapper.FilterbankOptions_feature_channels_set)
    __swig_setmethods__["window_size"] = _filterbank_wrapper.FilterbankOptions_window_size_set
    __swig_getmethods__["window_size"] = _filterbank_wrapper.FilterbankOptions_window_size_get
    if _newclass:
        window_size = _swig_property(_filterbank_wrapper.FilterbankOptions_window_size_get, _filterbank_wrapper.FilterbankOptions_window_size_set)
    __swig_setmethods__["window_step"] = _filterbank_wrapper.FilterbankOptions_window_step_set
    __swig_getmethods__["window_step"] = _filterbank_wrapper.FilterbankOptions_window_step_get
    if _newclass:
        window_step = _swig_property(_filterbank_wrapper.FilterbankOptions_window_step_get, _filterbank_wrapper.FilterbankOptions_window_step_set)
    __swig_destroy__ = _filterbank_wrapper.delete_FilterbankOptions
    __del__ = lambda self: None
FilterbankOptions_swigregister = _filterbank_wrapper.FilterbankOptions_swigregister
FilterbankOptions_swigregister(FilterbankOptions)

class Filterbank(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Filterbank, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Filterbank, name)
    __repr__ = _swig_repr

    def __init__(self, options):
        this = _filterbank_wrapper.new_Filterbank(options)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def Reset(self):
        return _filterbank_wrapper.Filterbank_Reset(self)

    def Compute(self, audio):
        return _filterbank_wrapper.Filterbank_Compute(self, audio)

    def options(self):
        return _filterbank_wrapper.Filterbank_options(self)
    __swig_destroy__ = _filterbank_wrapper.delete_Filterbank
    __del__ = lambda self: None
Filterbank_swigregister = _filterbank_wrapper.Filterbank_swigregister
Filterbank_swigregister(Filterbank)

# This file is compatible with both classic and new-style classes.


